### ISSUE TITLE
Directory not found for option 'ndnrtc-env/webrtc-checkout/src/out/Default/allibs'

### ISSUE THREAD

**Issue by travLappy** [remap/ndnrtc#12]
I am trying to compile NDN-RTC on Mac OSX 10.13.2, but on the **make** command in the section after #4 Libconfig, I get this error:

> 1 warning generated.
  CXX      src/libndnrtc_la-video-thread.lo
In file included from src/video-thread.cpp:14:
./src/video-thread.hpp:50:10: warning: using shared pointer here as libstdc++ on OSX does not support std::move [-W#warnings]
        #warning using shared pointer here as libstdc++ on OSX does not support std::move
         ^
1 warning generated.
  CXX      src/libndnrtc_la-webrtc-audio-channel.lo
  CXXLD    libndnrtc.la
ld: warning: directory not found for option '-L/Users/Username/ndnrtc-env/webrtc-checkout/src/out/Default/allibs'
ld: library not found for -lana_config_proto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libndnrtc.la] Error 1

I then navigate to the /Default directory and find that the '/allibs' directory is indeed not there. I checked out the branch-heads/59 version for WebRTC like the instructions said, so I'm not sure what the issue is. Everything compiled and installed successfully up to this point.

**Comment by peetonn** [comment]
did you complete step #1 fully (additional steps for macOS)?

`mkdir -p out/Default/allibs && for lib in `find out/Default -name "*.a"`; do cp $lib out/Default/allibs/; done;`
